export const environment = {
  production: true,
  STRIPE_KEY:'pk_live_51PDu03RseARsWMnZ1OXQDWwnw0j3gRIOn6Scf5nvLZmeZHDsF4zKpxQHhjCRi9yJLtcjvCSnCP7irNxzgogEkoXg00G37VGLBn',
  STRIPE_SECRET:'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',
};
